nodeLinker: node-modules

# 使用淘宝镜像加速
npmRegistryServer: "https://registry.npmmirror.com"

# 忽略引擎检查
enableGlobalCache: true

npmScopes:
  vantacore:
    npmPublishRegistry: "https://registry.npmjs.org"
